name: CodeReviewHub

services:
  codereviewhub:
    image: ${REGISTRY}/codereviewhub:latest
    pull_policy: always
    container_name: codereviewhub
    restart: unless-stopped
    expose:
      - 3000
    cpus: 0.5
    mem_limit: 384m
    mem_reservation: 256m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - NEXTAUTH_URL=https://codereviewhub.prathameshdhande.com
      - BASE_URL=https://codereviewhub.prathameshdhande.com
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=443
      - MINIO_USE_SSL=true
      - SMTP_HOST=smtp.resend.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM_NAME=CodeReview Hub
      - EMAIL_FROM_ADDRESS=no-reply@projects.prathameshdhande.com
      - EMAIL_REPLY_TO=prathameshdhande534@gmail.com
    networks:
      - proxy
      - pg-database
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.codereviewhub.rule=Host(`codereviewhub.prathameshdhande.com`)
      - traefik.http.routers.codereviewhub.entrypoints=https
      - traefik.http.routers.codereviewhub.tls=true
      - traefik.http.routers.codereviewhub.tls.certresolver=spaceship
      - traefik.http.routers.middlewares=codereviewhub-middleware
      - traefik.http.middlewares.codereviewhub-middleware.ratelimit.average=40
      - traefik.http.middlewares.codereviewhub-middleware.ratelimit.period=1s
      - traefik.http.middlewares.codereviewhub-middleware.ratelimit.burst=20

networks:
  proxy:
    external: true
  pg-database:
    external: true
